/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const changeUrgencyDueToSubject = require('./code/changeUrgencyDueToSubject');

class Processor extends LCAPApplicationService {
    async init() {

        this.on(['CREATE', 'UPDATE'], 'Incidents', async (request, next) => {
            await changeUrgencyDueToSubject(request);
            return next();
        });

        return super.init();
    }
}


module.exports = {
    Processor
};